CREATE TABLE IF NOT EXISTS permissions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  resource TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role TEXT NOT NULL,
  permission_id TEXT NOT NULL,
  granted BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (role, permission_id),
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

INSERT INTO permissions (id, name, description, category, resource, action) VALUES
('dashboard.view', 'View Dashboard', 'Access main dashboard and overview', 'Dashboard', 'dashboard', 'view'),
('dashboard.export', 'Export Dashboard Data', 'Export dashboard data and reports', 'Dashboard', 'dashboard', 'export'),
('vulnerabilities.view', 'View Vulnerabilities', 'View vulnerability reports and details', 'Vulnerabilities', 'vulnerabilities', 'view'),
('vulnerabilities.triage', 'Triage Vulnerabilities', 'Assign and prioritize vulnerabilities', 'Vulnerabilities', 'vulnerabilities', 'triage'),
('vulnerabilities.resolve', 'Resolve Vulnerabilities', 'Mark vulnerabilities as resolved', 'Vulnerabilities', 'vulnerabilities', 'resolve'),
('vulnerabilities.delete', 'Delete Vulnerabilities', 'Delete vulnerability records', 'Vulnerabilities', 'vulnerabilities', 'delete'),
('endpoints.view', 'View Endpoints', 'View endpoint inventory and details', 'Endpoints', 'endpoints', 'view'),
('endpoints.manage', 'Manage Endpoints', 'Add, edit, and remove endpoints', 'Endpoints', 'endpoints', 'manage'),
('endpoints.scan', 'Scan Endpoints', 'Initiate vulnerability scans', 'Endpoints', 'endpoints', 'scan'),
('users.view', 'View Users', 'View user accounts and profiles', 'User Management', 'users', 'view'),
('users.create', 'Create Users', 'Create new user accounts', 'User Management', 'users', 'create'),
('users.edit', 'Edit Users', 'Modify user accounts and roles', 'User Management', 'users', 'edit'),
('users.delete', 'Delete Users', 'Delete user accounts', 'User Management', 'users', 'delete'),
('users.permissions', 'Manage Permissions', 'Modify user permissions and access control', 'User Management', 'users', 'permissions'),
('reports.view', 'View Reports', 'Access security reports and analytics', 'Reports', 'reports', 'view'),
('reports.create', 'Create Reports', 'Generate custom reports', 'Reports', 'reports', 'create'),
('reports.export', 'Export Reports', 'Export reports in various formats', 'Reports', 'reports', 'export'),
('reports.schedule', 'Schedule Reports', 'Set up automated report generation', 'Reports', 'reports', 'schedule'),
('system.config', 'System Configuration', 'Modify system settings and configuration', 'System', 'system', 'config'),
('system.logs', 'View System Logs', 'Access system and audit logs', 'System', 'system', 'logs'),
('system.backup', 'System Backup', 'Create and manage system backups', 'System', 'system', 'backup'),
('system.maintenance', 'System Maintenance', 'Perform system maintenance tasks', 'System', 'system', 'maintenance'),
('api.access', 'API Access', 'Access REST API endpoints', 'API', 'api', 'access'),
('api.keys', 'Manage API Keys', 'Create and manage API keys', 'API', 'api', 'keys'),
('integrations.manage', 'Manage Integrations', 'Configure third-party integrations', 'API', 'integrations', 'manage');

INSERT INTO role_permissions (role, permission_id, granted) VALUES
('admin', 'dashboard.view', true),
('admin', 'dashboard.export', true),
('admin', 'vulnerabilities.view', true),
('admin', 'vulnerabilities.triage', true),
('admin', 'vulnerabilities.resolve', true),
('admin', 'vulnerabilities.delete', true),
('admin', 'endpoints.view', true),
('admin', 'endpoints.manage', true),
('admin', 'endpoints.scan', true),
('admin', 'users.view', true),
('admin', 'users.create', true),
('admin', 'users.edit', true),
('admin', 'users.delete', true),
('admin', 'users.permissions', true),
('admin', 'reports.view', true),
('admin', 'reports.create', true),
('admin', 'reports.export', true),
('admin', 'reports.schedule', true),
('admin', 'system.config', true),
('admin', 'system.logs', true),
('admin', 'system.backup', true),
('admin', 'system.maintenance', true),
('admin', 'api.access', true),
('admin', 'api.keys', true),
('admin', 'integrations.manage', true),
('analyst', 'dashboard.view', true),
('analyst', 'dashboard.export', true),
('analyst', 'vulnerabilities.view', true),
('analyst', 'vulnerabilities.triage', true),
('analyst', 'vulnerabilities.resolve', true),
('analyst', 'endpoints.view', true),
('analyst', 'endpoints.scan', true),
('analyst', 'users.view', true),
('analyst', 'reports.view', true),
('analyst', 'reports.create', true),
('analyst', 'reports.export', true),
('analyst', 'system.logs', true),
('analyst', 'api.access', true),
('viewer', 'dashboard.view', true),
('viewer', 'vulnerabilities.view', true),
('viewer', 'endpoints.view', true),
('viewer', 'users.view', true),
('viewer', 'reports.view', true);

alter publication supabase_realtime add table permissions;
alter publication supabase_realtime add table role_permissions;